:boom: Refactored project structure.

diff --git a/{{cookiecutter.project_slug}}/Dockerfile b/{{cookiecutter.project_slug}}/Dockerfile
--- a/{{cookiecutter.project_slug}}/Dockerfile
+++ b/{{cookiecutter.project_slug}}/Dockerfile
@@ -1,28 +1,29 @@
-ARG BASE_IMAGE=debian:12.1-slim
+# syntax=docker/dockerfile:1
+
+ARG BASE_IMAGE=ubuntu:22.04
+
 ARG DEBIAN_FRONTEND=noninteractive
-
-ARG {{cookiecutter.env_prefix}}APP_DIR="/app"
-ARG {{cookiecutter.env_prefix}}APP_HOME="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DIR}/{{cookiecutter.project_slug}}"
-ARG {{cookiecutter.env_prefix}}APP_DATA_DIR="/var/lib/{{cookiecutter.project_slug}}"
-ARG {{cookiecutter.env_prefix}}APP_LOGS_DIR="/var/log/{{cookiecutter.project_slug}}"
+ARG {{cookiecutter.env_prefix}}API_SLUG="{{cookiecutter.project_slug}}"
 
 
-# Here is the builder image
-# hadolint ignore=DL3006
-FROM ${BASE_IMAGE} as builder
+## Here is the builder image:
+FROM ${BASE_IMAGE} AS builder
 
 ARG DEBIAN_FRONTEND
+ARG {{cookiecutter.env_prefix}}API_SLUG
 
 # ARG USE_GPU=false
-ARG PYTHON_VERSION=3.9.18
+ARG PYTHON_VERSION={{cookiecutter.python_version}}
 
-# Set the SHELL to bash with pipefail option
 SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
-# hadolint ignore=DL3008
-RUN _BUILD_TARGET_ARCH=$(uname -m) && \
+WORKDIR "/usr/src/{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_SLUG}"
+
+RUN --mount=type=cache,target=/opt/conda/pkgs,sharing=private \
+	--mount=type=cache,target=/root/.cache,sharing=locked \
+	_BUILD_TARGET_ARCH=$(uname -m) && \
 	echo "BUILDING TARGET ARCHITECTURE: ${_BUILD_TARGET_ARCH}" && \
-	rm -rfv /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /root/.cache/* && \
+	rm -rfv /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* && \
 	apt-get clean -y && \
 	apt-get update --fix-missing -o Acquire::CompressionTypes::Order::=gz && \
 	apt-get install -y --no-install-recommends \
@@ -30,72 +31,79 @@ RUN _BUILD_TARGET_ARCH=$(uname -m) && \
 		build-essential \
 		wget && \
 	if [ "${_BUILD_TARGET_ARCH}" == "x86_64" ]; then \
-		export _MINICONDA_URL=https://repo.anaconda.com/miniconda/Miniconda3-py39_23.5.2-0-Linux-x86_64.sh; \
+		export _MINICONDA_FILENAME=Miniconda3-py39_24.9.2-0-Linux-x86_64.sh; \
+		export _MINICONDA_URL=https://repo.anaconda.com/miniconda/${_MINICONDA_FILENAME}; \
 	elif [ "${_BUILD_TARGET_ARCH}" == "aarch64" ]; then \
-		export _MINICONDA_URL=https://repo.anaconda.com/miniconda/Miniconda3-py39_23.5.2-0-Linux-aarch64.sh; \
-		# export _MINICONDA_URL=https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge-pypy3-Linux-aarch64.sh; \
+		export _MINICONDA_FILENAME=Miniconda3-py39_24.9.2-0-Linux-aarch64.sh; \
+		export _MINICONDA_URL=https://repo.anaconda.com/miniconda/${_MINICONDA_FILENAME}; \
+		# export _MINICONDA_FILENAME=Miniforge3-24.9.2-0-Linux-aarch64.sh; \
+		# export _MINICONDA_URL=https://github.com/conda-forge/miniforge/releases/download/24.9.2-0/${_MINICONDA_FILENAME}; \
 	else \
 		echo "Unsupported platform: ${_BUILD_TARGET_ARCH}" && \
 		exit 1; \
 	fi && \
-	wget -nv --show-progress --progress=bar:force:noscroll "${_MINICONDA_URL}" -O /root/miniconda.sh && \
-	/bin/bash /root/miniconda.sh -b -u -p /opt/conda && \
-	/opt/conda/condabin/conda clean -y -av && \
+	if [ ! -f "/root/.cache/${_MINICONDA_FILENAME}" ]; then \
+		wget -nv --show-progress --progress=bar:force:noscroll "${_MINICONDA_URL}" -O "/root/.cache/${_MINICONDA_FILENAME}"; \
+	fi && \
+	/bin/bash "/root/.cache/${_MINICONDA_FILENAME}" -b -u -p /opt/conda && \
 	/opt/conda/condabin/conda update -y conda && \
 	/opt/conda/condabin/conda install -y python=${PYTHON_VERSION} pip && \
-	/opt/conda/bin/pip install --timeout 60 --no-cache-dir -U pip && \
-	/opt/conda/bin/pip cache purge && \
-	/opt/conda/condabin/conda clean -y -av
+	/opt/conda/bin/pip install --timeout 60 -U pip
 
-COPY ./requirements*.txt /
-RUN	_BUILD_TARGET_ARCH=$(uname -m) && \
+# COPY ./requirements* ./
+RUN	--mount=type=cache,target=/root/.cache,sharing=locked \
+	--mount=type=bind,source=requirements.txt,target=requirements.txt \
+	# _BUILD_TARGET_ARCH=$(uname -m) && \
 	# if [ "${_BUILD_TARGET_ARCH}" == "x86_64" ] && [ "${USE_GPU}" == "false" ]; then \
-	# 	export _REQUIRE_FILENAME=requirements.amd64.txt; \
+	# 	export _REQUIRE_FILE_PATH=./requirements/requirements.amd64.txt; \
 	# elif [ "${_BUILD_TARGET_ARCH}" == "x86_64" ] && [ "${USE_GPU}" == "true" ]; then \
-	# 	export _REQUIRE_FILENAME=requirements.gpu.txt; \
+	# 	export _REQUIRE_FILE_PATH=./requirements/requirements.gpu.txt; \
 	# elif [ "${_BUILD_TARGET_ARCH}" == "aarch64" ]; then \
-	# 	export _REQUIRE_FILENAME=requirements.arm64.txt; \
+	# 	export _REQUIRE_FILE_PATH=./requirements/requirements.arm64.txt; \
 	# fi && \
-	# /opt/conda/bin/pip install --timeout 60 --no-cache-dir -r "./${_REQUIRE_FILENAME}" && \
-	/opt/conda/bin/pip install --timeout 60 --no-cache-dir -r ./requirements.txt && \
-	/opt/conda/bin/pip cache purge && \
-	/opt/conda/condabin/conda clean -y -av
+	# /opt/conda/bin/pip install --timeout 60 -r "${_REQUIRE_FILE_PATH}" && \
+	/opt/conda/bin/pip install --timeout 60 -r ./requirements.txt
 
 
-# Here is the base image
-# hadolint ignore=DL3006
-FROM ${BASE_IMAGE} as base
+## Here is the base image:
+FROM ${BASE_IMAGE} AS base
 
 ARG DEBIAN_FRONTEND
-ARG {{cookiecutter.env_prefix}}APP_DIR
-ARG {{cookiecutter.env_prefix}}APP_HOME
-ARG {{cookiecutter.env_prefix}}APP_DATA_DIR
-ARG {{cookiecutter.env_prefix}}APP_LOGS_DIR
+ARG {{cookiecutter.env_prefix}}API_SLUG
 
-# CHANGEME: Change hashed password:
-ARG HASH_PASSWORD="\$1\$K4Iyj0KF\$SyXMbO1NTSeKzng1TBzHt."
+ARG {{cookiecutter.env_prefix}}HOME_DIR="/app"
+ARG {{cookiecutter.env_prefix}}API_DIR="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}HOME_DIR}/{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_SLUG}"
+ARG {{cookiecutter.env_prefix}}API_DATA_DIR="/var/lib/{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_SLUG}"
+ARG {{cookiecutter.env_prefix}}API_LOGS_DIR="/var/log/{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_SLUG}"
+ARG {{cookiecutter.env_prefix}}API_TMP_DIR="/tmp/{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_SLUG}"
+# ARG {{cookiecutter.env_prefix}}API_MODELS_DIR="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DATA_DIR}/models"
+ARG {{cookiecutter.env_prefix}}API_PORT=8000
+## IMPORTANT!: Get hashed password from build-arg!
+## echo "{{cookiecutter.env_prefix}}USER_PASSWORD123" | openssl passwd -5 -stdin
+ARG HASH_PASSWORD="\$5\$UN1S7dZEa/qDoijJ\$hJ5o.Wpp5aP2kp.46Y7lWgcsRE8/oRLVswU6Swi13fB"
 ARG UID=1000
 ARG GID=11000
 ARG USER={{cookiecutter.project_abbr}}-user
 ARG GROUP={{cookiecutter.project_abbr}}-group
 
-ENV UID=${UID} \
+ENV {{cookiecutter.env_prefix}}HOME_DIR="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}HOME_DIR}" \
+	{{cookiecutter.env_prefix}}API_DIR="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DIR}" \
+	{{cookiecutter.env_prefix}}API_DATA_DIR="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DATA_DIR}" \
+	{{cookiecutter.env_prefix}}API_LOGS_DIR="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_LOGS_DIR}" \
+	{{cookiecutter.env_prefix}}API_TMP_DIR="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_TMP_DIR}" \
+	{{cookiecutter.env_prefix}}API_PORT={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_PORT} \
+	UID=${UID} \
 	GID=${GID} \
 	USER=${USER} \
 	GROUP=${GROUP} \
-	{{cookiecutter.env_prefix}}APP_DIR={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DIR} \
-	{{cookiecutter.env_prefix}}APP_HOME={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_HOME} \
-	{{cookiecutter.env_prefix}}APP_DATA_DIR={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DATA_DIR} \
-	{{cookiecutter.env_prefix}}APP_LOGS_DIR={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_LOGS_DIR}
+	PYTHONIOENCODING=utf-8 \
+	PYTHONUNBUFFERED=1 \
+	PATH="/opt/conda/bin:${PATH}"
 
-ENV	PYTHONIOENCODING=utf-8 \
-	PATH=/opt/conda/bin:${PATH}
+# ENV {{cookiecutter.env_prefix}}API_MODELS_DIR="{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_MODELS_DIR}"
 
-# Set the SHELL to bash with pipefail option
 SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
-# Installing system dependencies
-# hadolint ignore=DL3008
 RUN rm -rfv /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /root/.cache/* && \
 	apt-get clean -y && \
 	apt-get update --fix-missing -o Acquire::CompressionTypes::Order::=gz && \
@@ -111,45 +119,51 @@ RUN rm -rfv /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /root/.cache/*
 	apt-get clean -y && \
 	sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
 	sed -i -e 's/# en_AU.UTF-8 UTF-8/en_AU.UTF-8 UTF-8/' /etc/locale.gen && \
+	sed -i -e 's/# ko_KR.UTF-8 UTF-8/ko_KR.UTF-8 UTF-8/' /etc/locale.gen && \
 	dpkg-reconfigure --frontend=noninteractive locales && \
 	update-locale LANG=en_US.UTF-8 && \
 	echo "LANGUAGE=en_US.UTF-8" >> /etc/default/locale && \
 	echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale && \
 	addgroup --gid ${GID} ${GROUP} && \
-	useradd -l -m -d /home/${USER} -s /bin/bash -g ${GROUP} -G sudo -u ${UID} ${USER} && \
-	echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER} && \
-	chmod 0440 /etc/sudoers.d/${USER} && \
+	useradd -lmN -d "/home/${USER}" -s /bin/bash -g ${GROUP} -G sudo -u ${UID} ${USER} && \
+	echo "${USER} ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/${USER}" && \
+	chmod 0440 "/etc/sudoers.d/${USER}" && \
 	echo -e "${USER}:${HASH_PASSWORD}" | chpasswd -e && \
-	echo -e "\numask 0002" >> /home/${USER}/.bashrc && \
-	echo "alias ls='ls -aF --group-directories-first --color=auto'" >> /home/${USER}/.bashrc && \
-	echo -e "alias ll='ls -alhF --group-directories-first --color=auto'\n" >> /home/${USER}/.bashrc && \
-	echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/${USER}/.bashrc && \
-	echo "conda activate base" >> /home/${USER}/.bashrc && \
-	mkdir -pv {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_HOME} {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DATA_DIR} {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_LOGS_DIR} && \
-	chown -Rc "${USER}:${GROUP}" {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DIR} {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DATA_DIR} {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_LOGS_DIR} && \
-	find {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DIR} {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DATA_DIR} -type d -exec chmod -c 770 {} + && \
-	find {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DIR} {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DATA_DIR} -type d -exec chmod -c ug+s {} + && \
-	find {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_LOGS_DIR} -type d -exec chmod -c 775 {} + && \
-	find {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_LOGS_DIR} -type d -exec chmod -c +s {} + && \
-	rm -rfv /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /root/.cache/* /home/${USER}/.cache/*
+	echo -e "\nalias ls='ls -aF --group-directories-first --color=auto'" >> /root/.bashrc && \
+	echo -e "alias ll='ls -alhF --group-directories-first --color=auto'\n" >> /root/.bashrc && \
+	echo -e "\numask 0002" >> "/home/${USER}/.bashrc" && \
+	echo "alias ls='ls -aF --group-directories-first --color=auto'" >> "/home/${USER}/.bashrc" && \
+	echo -e "alias ll='ls -alhF --group-directories-first --color=auto'\n" >> "/home/${USER}/.bashrc" && \
+	echo ". /opt/conda/etc/profile.d/conda.sh" >> "/home/${USER}/.bashrc" && \
+	echo "conda activate base" >> "/home/${USER}/.bashrc" && \
+	rm -rfv /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* /root/.cache/* "/home/${USER}/.cache/*" && \
+	mkdir -pv "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DATA_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_LOGS_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_TMP_DIR}" && \
+	chown -Rc "${USER}:${GROUP}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}HOME_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DATA_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_LOGS_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_TMP_DIR}" && \
+	find "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DATA_DIR}" -type d -exec chmod -c 770 {} + && \
+	find "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DATA_DIR}" -type d -exec chmod -c ug+s {} + && \
+	find "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_LOGS_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_TMP_DIR}" -type d -exec chmod -c 775 {} + && \
+	find "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_LOGS_DIR}" "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_TMP_DIR}" -type d -exec chmod -c +s {} +
 
 ENV LANG=en_US.UTF-8 \
 	LANGUAGE=en_US.UTF-8 \
 	LC_ALL=en_US.UTF-8
 
-COPY --from=builder --chown=${UID}:${GID} /opt /opt
+COPY --from=builder --chown=${UID}:${GID} /opt/conda /opt/conda
 
 
-# Here is the production image
-# hadolint ignore=DL3006
-FROM base as app
+## Here is the final image:
+FROM base AS app
 
-WORKDIR {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_HOME}
-COPY --chown=${UID}:${GID} ./app {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_HOME}
+WORKDIR "{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DIR}"
+COPY --chown=${UID}:${GID} ./src {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DIR}
 COPY --chown=${UID}:${GID} --chmod=770 ./scripts/docker/*.sh /usr/local/bin/
 
-# VOLUME {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_DATA_DIR}
+# VOLUME ["{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_DATA_DIR}"]
+# EXPOSE {% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_PORT}
 
 USER ${UID}:${GID}
+# HEALTHCHECK --start-period=30s --start-interval=1s --interval=5m --timeout=5s --retries=3 \
+# 	CMD curl -f http://localhost:{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_PORT}/api/v{% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_VERSION:-1}/ping || exit 1
+
 ENTRYPOINT ["docker-entrypoint.sh"]
-# CMD ["-b", "sleep 1 && uvicorn main:app --host=0.0.0.0 --port={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}APP_PORT:-8000} --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log"]
+# CMD ["-b", "fastapi run --port={% raw %}${{% endraw %}{{cookiecutter.env_prefix}}API_PORT:-8000}"]
